apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/tolerations: |
      [
        {
          "key": "dedicated",
          "operator": "Equal",
          "value": "master",
          "effect": "NoSchedule"
        }
      ]
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: ""
  generation: 1
  labels:
    app: alb-ingress-controller
  name: alb-ingress-controller
  namespace: kube-system
  resourceVersion: "20252068"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/alb-ingress-controller
  uid: 79017dad-7dd9-11e8-9bb0-023f81959bd4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alb-ingress-controller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alb-ingress-controller
    spec:
      nodeSelector:
        dedicated: master
      containers:
      - args:
        - /server
        - --default-backend-service=kube-system/ingress-http-backend
        env:
        - name: AWS_REGION
          value: us-west-2
        - name: CLUSTER_NAME
          value: k8s.synup.com
        - name: AWS_DEBUG
          value: "false"
        - name: AWS_MAX_RETRIES
          value: "20"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/coreos/alb-ingress-controller:1.0-beta.2
        imagePullPolicy: Always
        name: server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/role: master
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: alb-service-account
      serviceAccountName: alb-service-account
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists